# Generated by Django 4.2 on 2024-03-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='orders.order'),
        ),
    ]
