# Generated by Django 4.2 on 2024-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Product',
            new_name='product',
        ),
    ]
