# Generated by Django 4.2 on 2024-03-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_product_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='Product',
            new_name='product',
        ),
    ]
