# Generated by Django 4.2 on 2024-03-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_review_created_at_review_create_at'),
        ('orders', '0008_alter_cartdetail_quantity_alter_cartdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='products.product'),
        ),
    ]
